#!/bin/bash
Module_Caption+=" -> $(basename $0)"
echo $Module_Caption
sleep 15
Lock_hl=1

Module_Info_2="echo 'Select programs (Space) and install (Enter):'"

cd "${Path_Install}/programs"
source ${Path_Install}/litenavi/litenavi.sh
for Program in ${LN_Output}; do
    [[ -z "$(pacman -Qi ${Program} 2> /dev/null)" ]] && ${Path_Install}/programs/${Program}/i.sh 
done
