#!/bin/bash
Lock=1
cd "${Path_Install}/programs"
source ${Path_Install}/litenavi/litenavi.sh
echo ${LN_Output}
sleep 3
for Program in ${LN_Output}; do
    [[ -z "$(pacman -Qi ${Program})" ]] && ${Path_Install}/programs/${Program}/i.sh 
    sleep 5
done
