#!/bin/bash
Lock=1
cd "${Path_Install}/programs"
echo !!!!!!!!!!!!!!!!!!1
sleep 2
source ${Path_Install}/litenavi/litenavi.sh
echo ${LN_Output}
sleep 2
for Program in ${LN_Output}; do
    [[ -z "$(pacman -Qi ${Program})" ]] && pacman -Qi ${Program} 
done
sleep 2
