#!/bin/bash
#boot,mbr_grub,root,swap+home

## выбор диска для системы, определение размера диска под систему в мегабайтах. ввод из текущего терминала. 
echo
lsblk -S | awk '$3=="disk" || NR==1 {print $0}'
echo
PS3=$(echo -e "${R}${Q1111} [boot,mbr_grub,root+swap]: ${NC}")
select SYSTEM_DISK in $(lsblk -Sln | awk '$3=="disk" {print $1}'); do
    [[ -n ${SYSTEM_DISK} ]] && break
done

## выбор диска с домашней директорией. ввод из текущего терминала.
echo; lsblk -S | awk '$3=="disk" || NR==1 {print $0}'; echo
PS3=$( echo -e "${R}${Q1111} [home]: ${NC}")
select HOME_DISK in $(lsblk -Sln | awk -v ex="${SYSTEM_DISK}" '$3=="disk" || $1!=ex {print $1}'); do
    [[ -n $HOME_DISK ]] && break
done

## размонтирование swap  
while [[ -n $(swapon --show=NAME --noheadings) ]]; do
    swapoff $(swapon --show=NAME --noheadings)
done
    
## размонтирование разделов выбранных дисков
while [[ -n $(lsblk -ln /dev/${SYSTEM_DISK} /dev/${HOME_DISK} | awk '$6=="part" && $7 {print $1}') ]]; do
    for PART in $(lsblk -ln /dev/${SYSTEM_DISK} /dev/${HOME_DISK} | awk '$6=="part" && $7 {print $1}') ]]; do
        fuser -km /dev/${PART}
        umount -l /dev/${PART} 
    done
done

## разметка системного диска
SYSTEM_DISK_SIZE=$(($(lsblk -lbn /dev/${SYSTEM_DISK} | awk '$6=="disk" {print $4}') / (1024**2))) 
BOOT_SIZE=200
MBR_GRUB_SIZE=1
SWAP_SIZE=$(($(cat /proc/meminfo | awk '$1=="MemTotal:" {print $2}') / 1024))
ROOT_SIZE=$((${SYSTEM_DISK_SIZE} - ${SWAP_SIZE} - ${BOOT_SIZE} - ${MBR_GRUB_SIZE}))

until [[ $(lsblk -ln /dev/${SYSTEM_DISK} | grep "part" -c) = "4" ]]; do
    echo -e "g\nw\n" | fdisk /dev/${SYSTEM_DISK} # создаём gpt
    echo -e "n\n1\n\n+"${BOOT_SIZE}"M\nw\n" | fdisk /dev/${SYSTEM_DISK} # /boot
    echo -e "n\n2\n\n+"${MBR_GRUB_SIZE}"M\nt\n2\n4\nw\n" | fdisk /dev/${SYSTEM_DISK} # раздел для mbr grub
    echo -e "n\n3\n\n+"${ROOT_SIZE}"M\nw\n" | fdisk /dev/${SYSTEM_DISK} # /
    echo -e "n\n4\n\n\nw\n" | fdisk /dev/${SYSTEM_DISK} # swap
done

## создание файловых систем
mkfs.ext2 -L boot /dev/"${SYSTEM_DISK}"'1' <<< Y
sed -i "s/BOOT_PART=.*$/BOOT_PART=\"\/dev\/${SYSTEM_DISK}\"/" ${HOME}/install/mawbah/mawbah.conf
mkfs.ext4 -L root /dev/"${SYSTEM_DISK}"'3' <<< Y
mkswap -L swap /dev/"${SYSTEM_DISK}"'4'<<< Y

## проверка и отключение необходимых точек монтирования 
while [[ -n $(lsblk -ln | awk '$7=="/" || $7=="/boot" || $7=="/home" || $7=="[SWAP]" {print $7}') ]]; do
    for MOUNT in $(lsblk -ln | awk '$7=="/" || $7=="/boot" || $7=="/home" || $7=="[SWAP]" {print $7}') ]]; do
        fuser -km ${MOUNT}
        umount -l ${MOUNT} 
    done
done

## монтирование разделов
mount /dev/"${SYSTEM_DISK}"'3' /mnt
mkdir /mnt/{home,boot}
mount /dev/"${SYSTEM_DISK}"'1' /mnt/boot
mount /dev/"${HOME_DISK}"'1' /mnt/home
swapon /dev/"${SYSTEM_DISK}"'4'
